#include <doca_argp.h>
#include <doca_dev.h>
#include <doca_dpdk.h>
#include <doca_flow.h>
#include <doca_log.h>
#include <rte_eal.h>
#include <rte_ethdev.h>
#include <rte_mbuf.h>
#include <signal.h>
#include <stdarg.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

DOCA_LOG_REGISTER(FLOW_ECN);

#define NB_QUEUES 1
#define NB_ENTRIES 1  /* single CE-mark entry: all IPv4 wire ingress → CE, regardless of ECT */
#define NB_COUNTERS 2 /* global counter pool: CE-mark entry + ingress-passthrough entry */

struct ecn_app_config {
  double random_percent; /* requested percentage of packets to mark, [0, 100] (see --percent) */
};

/* parser_meta.random is a 16-bit per-packet value generated by HW, independent of packet
 * content (see doca_flow.h). Matching it with a mask restricts to a fraction of traffic. */
#define RANDOM_FIELD_WIDTH 16

/*
 * Mask-based random matching only supports negative-power-of-two percentages
 * (50, 25, 12.5, ..., 0.0015%): rounds the requested percentage down to the nearest one.
 * Same technique as DOCA's own flow_random sample (doca_flow/flow_random/flow_random_sample.c).
 * Only called for 0 < percentage < 100 — the exact 0%/100% cases are special-cased in main()
 * to skip the RANDOM_SAMPLE pipe entirely instead of approximating with the smallest/largest
 * supported fraction.
 */
static uint16_t get_random_mask(double percentage) {
  double next_supported = 50.0;
  uint8_t i;

  for (i = 1; i <= RANDOM_FIELD_WIDTH; ++i) {
    if (percentage >= next_supported) {
      break;
    }
    next_supported /= 2;
  }
  if (percentage > next_supported) {
    DOCA_LOG_WARN("Requested %.4g%% sampling not supported (power-of-2 only); using %.4g%% instead", percentage, next_supported);
  }
  return (uint16_t)((1u << i) - 1);
}

static volatile bool g_running = true;

static void signal_handler(int signum) {
  if (signum == SIGINT || signum == SIGTERM) {
    g_running = false;
  }
}

/* Log at CRIT level and terminate if err != DOCA_SUCCESS — mirrors rte_exit(). */
static __attribute__((format(printf, 2, 3))) void crash_if_unsuccessful(doca_error_t err, const char *fmt, ...) {
  if (err == DOCA_SUCCESS) {
    return;
  }
  char msg[512];
  va_list args;
  va_start(args, fmt);
  vsnprintf(msg, sizeof(msg), fmt, args);
  va_end(args);

  DOCA_LOG_CRIT("%s: %s", msg, doca_error_get_descr(err));

  exit(EXIT_FAILURE);
}

/* DOCA Flow global entry-process callback — updates a per-batch status struct */
struct entry_batch_status {
  bool failure;
  uint32_t nb_processed;
};

static void entry_process_cb(struct doca_flow_pipe_entry *entry, uint16_t pipe_queue, enum doca_flow_entry_status status,
                             enum doca_flow_entry_op op, void *user_ctx) {
  (void)entry;
  (void)pipe_queue;
  (void)op;
  struct entry_batch_status *s = user_ctx;

  if (s == NULL) {
    return;
  }
  if (status != DOCA_FLOW_ENTRY_STATUS_SUCCESS) {
    s->failure = true;
  }
  s->nb_processed++;
}

/*
 * EAL callback: add a dummy -a allowlist entry so EAL does not auto-probe any real PCI devices.
 * Real devices are attached explicitly via doca_dpdk_port_probe after doca_dev_open.
 * This matches the DOCA SDK pattern used in flow_ct_dpdk_init.
 */
static doca_error_t initialize_dpdk(int argc, char **argv) {
  static char allow_flag[] = "-a";
  static char dummy_pci[] = "pci:00:00.0";
  char *new_argv[64];

  if (argc >= 62) {
    DOCA_LOG_ERR("Too many EAL arguments");
    return DOCA_ERROR_INVALID_VALUE;
  }
  for (int i = 0; i < argc; i++) {
    new_argv[i] = argv[i];
  }
  new_argv[argc] = allow_flag;
  new_argv[argc + 1] = dummy_pci;

  if (rte_eal_init(argc + 2, new_argv) < 0) {
    DOCA_LOG_ERR("EAL initialization failed");
    return DOCA_ERROR_DRIVER;
  }
  return DOCA_SUCCESS;
}

/* Open the Nth DOCA device and probe it into DPDK with caller-supplied args. */
static struct doca_dev *open_and_probe_dev(uint32_t index, const char *probe_args) {
  struct doca_devinfo **devinfo_list;
  uint32_t nb_devs;
  struct doca_dev *dev;
  doca_error_t err;

  err = doca_devinfo_create_list(&devinfo_list, &nb_devs);
  crash_if_unsuccessful(err, "doca_devinfo_create_list");

  if (index >= nb_devs) {
    DOCA_LOG_CRIT("Device index %u out of range (%u devices found)", index, nb_devs);
    exit(EXIT_FAILURE);
  }

  err = doca_dev_open(devinfo_list[index], &dev);
  crash_if_unsuccessful(err, "doca_dev_open");

  doca_devinfo_destroy_list(devinfo_list);

  err = doca_dpdk_port_probe(dev, probe_args);
  crash_if_unsuccessful(err, "doca_dpdk_port_probe (index=%u)", index);

  return dev;
}

/*
 * DPDK must be configured and started before DOCA Flow calls rte_flow_configure (HWS requirement).
 * DPDK also requires at least one RX queue to start a port.
 * This is the minimum setup needed — see gpu_packet_processing for the SDK reference.
 */
static void configure_and_start_dpdk_port(struct doca_dev *dev) {
  uint16_t first_port_id;
  doca_error_t err = doca_dpdk_get_first_port_id(dev, &first_port_id);
  crash_if_unsuccessful(err, "doca_dpdk_get_first_port_id");

  /* One shared mempool for all ports (PF + SF rep). */
  struct rte_mempool *mp =
      rte_pktmbuf_pool_create("mbuf_pool", 8192, 0, 0, RTE_MBUF_DEFAULT_BUF_SIZE, rte_eth_dev_socket_id(first_port_id));
  if (mp == NULL) {
    DOCA_LOG_CRIT("rte_pktmbuf_pool_create failed");
    exit(EXIT_FAILURE);
  }

  uint16_t port_id;
  RTE_ETH_FOREACH_DEV(port_id) {
    struct rte_eth_dev_info dev_info = {0};
    int ret = rte_eth_dev_info_get(port_id, &dev_info);
    if (ret < 0) {
      DOCA_LOG_CRIT("rte_eth_dev_info_get port %u failed (errno %d)", port_id, -ret);
      exit(EXIT_FAILURE);
    }

    struct rte_eth_conf eth_conf = {0};
    ret = rte_eth_dev_configure(port_id, NB_QUEUES, NB_QUEUES, &eth_conf);
    if (ret < 0) {
      DOCA_LOG_CRIT("rte_eth_dev_configure port %u failed (errno %d)", port_id, -ret);
      exit(EXIT_FAILURE);
    }

    struct rte_eth_txconf tx_conf = dev_info.default_txconf;
    for (int q = 0; q < NB_QUEUES; q++) {
      ret = rte_eth_rx_queue_setup(port_id, q, 512, rte_eth_dev_socket_id(port_id), NULL, mp);
      if (ret < 0) {
        DOCA_LOG_CRIT("rte_eth_rx_queue_setup port %u q%d failed (errno %d)", port_id, q, -ret);
        exit(EXIT_FAILURE);
      }
      ret = rte_eth_tx_queue_setup(port_id, q, 512, rte_eth_dev_socket_id(port_id), &tx_conf);
      if (ret < 0) {
        DOCA_LOG_CRIT("rte_eth_tx_queue_setup port %u q%d failed (errno %d)", port_id, q, -ret);
        exit(EXIT_FAILURE);
      }
    }

    ret = rte_eth_dev_start(port_id);
    if (ret < 0) {
      DOCA_LOG_CRIT("rte_eth_dev_start port %u failed (errno %d)", port_id, -ret);
      exit(EXIT_FAILURE);
    }
  }
}

static void initialize_doca_flow(void) {
  doca_error_t err;

  struct doca_flow_cfg *cfg;
  err = doca_flow_cfg_create(&cfg);
  crash_if_unsuccessful(err, "doca_flow_cfg_create");

  err = doca_flow_cfg_set_pipe_queues(cfg, NB_QUEUES);
  crash_if_unsuccessful(err, "doca_flow_cfg_set_pipe_queues");

  // switch mode: traffic forwarded between eSwitch ports; no CPU RSS queues needed
  err = doca_flow_cfg_set_mode_args(cfg, "switch,hws");
  crash_if_unsuccessful(err, "doca_flow_cfg_set_mode_args");

  err = doca_flow_cfg_set_nr_counters(cfg, NB_COUNTERS);
  crash_if_unsuccessful(err, "doca_flow_cfg_set_nr_counters");

  err = doca_flow_cfg_set_cb_entry_process(cfg, entry_process_cb);
  crash_if_unsuccessful(err, "doca_flow_cfg_set_cb_entry_process");

  err = doca_flow_init(cfg);
  crash_if_unsuccessful(err, "doca_flow_init");

  doca_flow_cfg_destroy(cfg);
}

static struct doca_flow_port *port_start(struct doca_dev *dev) {
  uint16_t port_id;
  doca_error_t err = doca_dpdk_get_first_port_id(dev, &port_id);
  crash_if_unsuccessful(err, "doca_dpdk_get_first_port_id");

  struct doca_flow_port_cfg *cfg;
  err = doca_flow_port_cfg_create(&cfg);
  crash_if_unsuccessful(err, "doca_flow_port_cfg_create");

  err = doca_flow_port_cfg_set_dev(cfg, dev);
  crash_if_unsuccessful(err, "doca_flow_port_cfg_set_dev");

  char port_id_str[8];
  snprintf(port_id_str, sizeof(port_id_str), "%u", port_id);

  err = doca_flow_port_cfg_set_devargs(cfg, port_id_str);
  crash_if_unsuccessful(err, "doca_flow_port_cfg_set_devargs");

  struct doca_flow_port *port;
  err = doca_flow_port_start(cfg, &port);
  crash_if_unsuccessful(err, "doca_flow_port_start");

  doca_flow_port_cfg_destroy(cfg);

  return port;
}

/* Start an arbitrary DPDK port as a DOCA Flow port (used for SF representors). */
static struct doca_flow_port *rep_port_start(uint16_t dpdk_port_id) {
  struct doca_flow_port_cfg *cfg;
  char port_id_str[8];
  snprintf(port_id_str, sizeof(port_id_str), "%u", dpdk_port_id);

  doca_error_t err = doca_flow_port_cfg_create(&cfg);
  crash_if_unsuccessful(err, "doca_flow_port_cfg_create (rep port %u)", dpdk_port_id);

  err = doca_flow_port_cfg_set_devargs(cfg, port_id_str);
  crash_if_unsuccessful(err, "doca_flow_port_cfg_set_devargs (rep port %u)", dpdk_port_id);

  struct doca_flow_port *port;
  err = doca_flow_port_start(cfg, &port);
  crash_if_unsuccessful(err, "doca_flow_port_start (rep port %u)", dpdk_port_id);

  doca_flow_port_cfg_destroy(cfg);
  return port;
}

/*
 * Create a forward-only pipe (no action template) that passes all IPv4 to dest_port_id,
 * completely untouched.
 *
 * Used as the miss target (INGRESS_PASSTHROUGH) for the ECN mark pipe: non-IPv4 and not-selected
 * wire packets reach mlx5_2 via port 1 as-is. No rewrite is needed to get there:
 * the wire already carries mlx5_2's real MAC (see README/setup_roce_loopback.sh), so the
 * ibverbs QP steering rule (which matches on dst MAC) fires without DOCA Flow's help.
 *
 * HWS requires a non-empty match template. We declare dscp_ecn as a variable field with
 * mask=0x00, making it a wildcard — the single entry we install catches all IPv4.
 */
static struct doca_flow_pipe *create_fwd_pipe(
    struct doca_flow_port *port, const char *name, enum doca_flow_pipe_domain domain, bool is_root, uint16_t dest_port_id,
    bool with_counter) /* attach a packet counter (queryable via doca_flow_resource_query_entry) */
{
  struct doca_flow_match match = {0};
  struct doca_flow_match match_mask = {0};
  struct doca_flow_monitor monitor = {.counter_type = DOCA_FLOW_RESOURCE_TYPE_NON_SHARED};
  struct doca_flow_fwd fwd = {.type = DOCA_FLOW_FWD_PORT, .port_id = dest_port_id};
  struct doca_flow_pipe_cfg *cfg;
  struct doca_flow_pipe *pipe;
  doca_error_t err;

  match.outer.l3_type = DOCA_FLOW_L3_TYPE_IP4;
  match.outer.ip4.dscp_ecn = 0xFF; /* variable field → non-empty HWS template */
  /* match_mask.outer.ip4.dscp_ecn = 0x00 (zero mask → match any TOS) */

  err = doca_flow_pipe_cfg_create(&cfg, port);
  crash_if_unsuccessful(err, "doca_flow_pipe_cfg_create (fwd pipe)");
  err = doca_flow_pipe_cfg_set_name(cfg, name);
  crash_if_unsuccessful(err, "doca_flow_pipe_cfg_set_name (fwd pipe)");
  err = doca_flow_pipe_cfg_set_type(cfg, DOCA_FLOW_PIPE_BASIC);
  crash_if_unsuccessful(err, "doca_flow_pipe_cfg_set_type (fwd pipe)");
  err = doca_flow_pipe_cfg_set_domain(cfg, domain);
  crash_if_unsuccessful(err, "doca_flow_pipe_cfg_set_domain (fwd pipe)");
  err = doca_flow_pipe_cfg_set_is_root(cfg, is_root);
  crash_if_unsuccessful(err, "doca_flow_pipe_cfg_set_is_root (fwd pipe)");
  err = doca_flow_pipe_cfg_set_nr_entries(cfg, 1);
  crash_if_unsuccessful(err, "doca_flow_pipe_cfg_set_nr_entries (fwd pipe)");
  err = doca_flow_pipe_cfg_set_match(cfg, &match, &match_mask);
  crash_if_unsuccessful(err, "doca_flow_pipe_cfg_set_match (fwd pipe)");
  if (with_counter) {
    err = doca_flow_pipe_cfg_set_monitor(cfg, &monitor);
    crash_if_unsuccessful(err, "doca_flow_pipe_cfg_set_monitor (fwd pipe %s)", name);
  }

  err = doca_flow_pipe_create(cfg, &fwd, NULL, &pipe);
  crash_if_unsuccessful(err, "doca_flow_pipe_create (fwd pipe %s)", name);

  doca_flow_pipe_cfg_destroy(cfg);
  return pipe;
}

/* Adds the pipe's single entry and returns it (for with_counter pipes, used for stats queries). */
static struct doca_flow_pipe_entry *add_fwd_entry(struct doca_flow_pipe *pipe, struct doca_flow_port *port, const char *label,
                                                  bool with_counter) {
  struct doca_flow_match match = {0};
  struct doca_flow_monitor monitor = {.counter_type = DOCA_FLOW_RESOURCE_TYPE_NON_SHARED};
  struct doca_flow_pipe_entry *entry;
  struct entry_batch_status status = {0};
  doca_error_t err;

  match.outer.l3_type = DOCA_FLOW_L3_TYPE_IP4;
  /* dscp_ecn left 0; mask=0x00 means any dscp_ecn matches → catches all IPv4 */

  err = doca_flow_pipe_basic_add_entry(0, pipe, &match, 0, NULL, with_counter ? &monitor : NULL, NULL, 0, &status,
                                       &entry);
  crash_if_unsuccessful(err, "doca_flow_pipe_basic_add_entry (%s)", label);

  err = doca_flow_entries_process(port, 0, 10000, 1);
  crash_if_unsuccessful(err, "doca_flow_entries_process (%s)", label);

  err = (status.failure || status.nb_processed != 1) ? DOCA_ERROR_BAD_STATE : DOCA_SUCCESS;
  crash_if_unsuccessful(err, "fwd entry installation (%s): %u processed", label, status.nb_processed);

  DOCA_LOG_INFO("Fwd pipe '%s' ready", label);
  return entry;
}

/*
 * Create a non-root pipe (reached from PORT_DEMUX for p0 wire ingress) that SETs CE on
 * all IPv4 packets before delivering them to mlx5_2 — the DPU injects the congestion
 * signal regardless of the sender's ECN bits. This deliberately departs from standard
 * ECN (a router may only promote ECT→CE) so that any RoCE generator drives the PCC loop:
 * tools like ib_send_bw send Not-ECT (00) traffic and cannot reliably stamp ECT here, so
 * strict ECT→CE marking would never fire for them. Setting CE (0x03) is a valid non-zero
 * write; only SET dscp_ecn=0 is hardware-restricted.
 *
 * Non-IPv4 packets miss this pipe and go to miss_pipe (forward-only, no rewrite). At 0 < percent
 * < 100, only the packets selected by RANDOM_SAMPLE (see create_random_sample_pipe) ever reach
 * this pipe at all — everything else is diverted to miss_pipe upstream, before here.
 */
static struct doca_flow_pipe *create_ecn_mark_pipe(struct doca_flow_port *port, struct doca_flow_pipe *miss_pipe) {
  struct doca_flow_match match = {0};
  struct doca_flow_match match_mask = {0};
  struct doca_flow_actions actions = {0}, *actions_arr[1] = {&actions};
  struct doca_flow_monitor monitor = {.counter_type = DOCA_FLOW_RESOURCE_TYPE_NON_SHARED};
  struct doca_flow_fwd fwd = {0};
  struct doca_flow_pipe_cfg *cfg;
  struct doca_flow_pipe *pipe;
  doca_error_t err;

  /*
   * Match all IPv4 packets. dscp_ecn is wildcarded (mask 0x00) so any ECN value —
   * Not-ECT, ECT(0/1), or already-CE — hits the single entry and gets marked CE.
   */
  match.outer.l3_type = DOCA_FLOW_L3_TYPE_IP4;
  match.outer.ip4.dscp_ecn = 0xFF;      /* wildcard field → non-empty HWS template */
  match_mask.outer.ip4.dscp_ecn = 0x00; /* mask 0 → match any dscp_ecn             */

  /* SET dscp_ecn=CE — exact value supplied per entry */
  actions.outer.l3_type = DOCA_FLOW_L3_TYPE_IP4;
  actions.outer.ip4.dscp_ecn = 0xFF; /* variable — overridden per entry */

  /* CE mark → deliver to SF0 rep (port 1 = en3f0pf0sf0 = mlx5_2, the ibverbs receiver) */
  fwd.type = DOCA_FLOW_FWD_PORT;
  fwd.port_id = 1;

  err = doca_flow_pipe_cfg_create(&cfg, port);
  crash_if_unsuccessful(err, "doca_flow_pipe_cfg_create");

  err = doca_flow_pipe_cfg_set_name(cfg, "ECN_MARK");
  crash_if_unsuccessful(err, "doca_flow_pipe_cfg_set_name");

  err = doca_flow_pipe_cfg_set_type(cfg, DOCA_FLOW_PIPE_BASIC);
  crash_if_unsuccessful(err, "doca_flow_pipe_cfg_set_type");

  err = doca_flow_pipe_cfg_set_domain(cfg, DOCA_FLOW_PIPE_DOMAIN_DEFAULT);
  crash_if_unsuccessful(err, "doca_flow_pipe_cfg_set_domain");

  err = doca_flow_pipe_cfg_set_is_root(cfg, false); /* root is PORT_DEMUX; reached via FWD_PIPE */
  crash_if_unsuccessful(err, "doca_flow_pipe_cfg_set_is_root");

  err = doca_flow_pipe_cfg_set_nr_entries(cfg, NB_ENTRIES);
  crash_if_unsuccessful(err, "doca_flow_pipe_cfg_set_nr_entries");

  err = doca_flow_pipe_cfg_set_match(cfg, &match, &match_mask);
  crash_if_unsuccessful(err, "doca_flow_pipe_cfg_set_match");

  err = doca_flow_pipe_cfg_set_actions(cfg, actions_arr, NULL, NULL, 1);
  crash_if_unsuccessful(err, "doca_flow_pipe_cfg_set_actions");

  err = doca_flow_pipe_cfg_set_monitor(cfg, &monitor);
  crash_if_unsuccessful(err, "doca_flow_pipe_cfg_set_monitor");

  /* Non-IPv4 miss → miss_pipe (forward-only, no rewrite) */
  struct doca_flow_fwd fwd_miss = {.type = DOCA_FLOW_FWD_PIPE, .next_pipe = miss_pipe};
  err = doca_flow_pipe_create(cfg, &fwd, &fwd_miss, &pipe);
  crash_if_unsuccessful(err, "doca_flow_pipe_create");

  doca_flow_pipe_cfg_destroy(cfg);
  return pipe;
}

struct ecn_entries {
  struct doca_flow_pipe_entry *ce;          /* CE-marked count */
  struct doca_flow_pipe_entry *passthrough; /* unmarked (missed) count */
};

static struct ecn_entries add_ecn_entries(struct doca_flow_pipe *pipe, struct doca_flow_port *port) {
  struct doca_flow_match match = {0};
  struct doca_flow_actions actions = {0};
  struct doca_flow_monitor monitor = {.counter_type = DOCA_FLOW_RESOURCE_TYPE_NON_SHARED};
  struct entry_batch_status status = {0};
  struct ecn_entries entries = {0}; /* .passthrough set by the caller once its pipe exists */
  doca_error_t err;

  actions.outer.l3_type = DOCA_FLOW_L3_TYPE_IP4;
  actions.outer.ip4.dscp_ecn = 0x03; /* SET to CE (DSCP=0, ECN=11) */

  /* Single entry: all IPv4 (dscp_ecn wildcarded by the pipe mask) → CE; flags=0 flushes */
  match.outer.ip4.dscp_ecn = 0x00; /* don't-care: pipe match_mask is 0x00 */
  err = doca_flow_pipe_basic_add_entry(0, pipe, &match, 0, &actions, &monitor, NULL, 0, &status, &entries.ce);
  crash_if_unsuccessful(err, "doca_flow_pipe_basic_add_entry CE");

  err = doca_flow_entries_process(port, 0, 10000 /* us */, NB_ENTRIES);
  crash_if_unsuccessful(err, "doca_flow_entries_process");
  err = (status.failure || status.nb_processed != NB_ENTRIES) ? DOCA_ERROR_BAD_STATE : DOCA_SUCCESS;
  crash_if_unsuccessful(err, "entry installation incomplete: %u/%u processed", status.nb_processed, NB_ENTRIES);

  DOCA_LOG_INFO("ECN mark pipe ready: all IPv4 → CE on p0 ingress (sender ECN ignored)");
  return entries;
}

/*
 * 0 < percent < 100: a dedicated pre-filter pipe that matches ONLY parser_meta.random (no
 * header fields, no actions) and forwards the selected fraction to hit_pipe (ECN_MARK) or
 * everything else to miss_pipe (INGRESS_PASSTHROUGH). Mirrors DOCA's own flow_random sample
 * (doca_flow/flow_random/flow_random_sample.c) exactly.
 *
 * Combining a parser_meta.random match with header-modify actions in a single HWS entry is
 * NOT supported on this firmware (verified: doca_flow_pipe_add_entry fails with rc=-22 /
 * EINVAL when ECN_MARK's own matcher also carries the random field) — hence the random
 * selection is split into this separate, action-free pipe upstream of ECN_MARK instead.
 */
static struct doca_flow_pipe *create_random_sample_pipe(struct doca_flow_port *port, struct doca_flow_pipe *hit_pipe,
                                                        struct doca_flow_pipe *miss_pipe, uint16_t random_mask) {
  struct doca_flow_match match = {0};
  struct doca_flow_match match_mask = {0};
  struct doca_flow_fwd fwd = {.type = DOCA_FLOW_FWD_PIPE, .next_pipe = hit_pipe};
  struct doca_flow_fwd fwd_miss = {.type = DOCA_FLOW_FWD_PIPE, .next_pipe = miss_pipe};
  struct doca_flow_pipe_cfg *cfg;
  struct doca_flow_pipe *pipe;
  struct doca_flow_pipe_entry *entry;
  struct entry_batch_status status = {0};
  doca_error_t err;

  match.parser_meta.random = 0;
  match_mask.parser_meta.random = random_mask;

  err = doca_flow_pipe_cfg_create(&cfg, port);
  crash_if_unsuccessful(err, "doca_flow_pipe_cfg_create (random sample)");
  err = doca_flow_pipe_cfg_set_name(cfg, "RANDOM_SAMPLE");
  crash_if_unsuccessful(err, "doca_flow_pipe_cfg_set_name (random sample)");
  err = doca_flow_pipe_cfg_set_type(cfg, DOCA_FLOW_PIPE_BASIC);
  crash_if_unsuccessful(err, "doca_flow_pipe_cfg_set_type (random sample)");
  err = doca_flow_pipe_cfg_set_domain(cfg, DOCA_FLOW_PIPE_DOMAIN_DEFAULT);
  crash_if_unsuccessful(err, "doca_flow_pipe_cfg_set_domain (random sample)");
  err = doca_flow_pipe_cfg_set_is_root(cfg, false); /* root is PORT_DEMUX; reached via FWD_PIPE */
  crash_if_unsuccessful(err, "doca_flow_pipe_cfg_set_is_root (random sample)");
  err = doca_flow_pipe_cfg_set_nr_entries(cfg, 1);
  crash_if_unsuccessful(err, "doca_flow_pipe_cfg_set_nr_entries (random sample)");
  err = doca_flow_pipe_cfg_set_match(cfg, &match, &match_mask);
  crash_if_unsuccessful(err, "doca_flow_pipe_cfg_set_match (random sample)");

  err = doca_flow_pipe_create(cfg, &fwd, &fwd_miss, &pipe);
  crash_if_unsuccessful(err, "doca_flow_pipe_create (random sample)");
  doca_flow_pipe_cfg_destroy(cfg);

  err = doca_flow_pipe_basic_add_entry(0, pipe, &match, 0, NULL, NULL, NULL, 0, &status, &entry);
  crash_if_unsuccessful(err, "doca_flow_pipe_basic_add_entry (random sample)");

  err = doca_flow_entries_process(port, 0, 10000, 1);
  crash_if_unsuccessful(err, "doca_flow_entries_process (random sample)");
  err = (status.failure || status.nb_processed != 1) ? DOCA_ERROR_BAD_STATE : DOCA_SUCCESS;
  crash_if_unsuccessful(err, "random sample entry installation: %u processed", status.nb_processed);

  DOCA_LOG_INFO("Random sample pipe ready: mask 0x%04x", random_mask);
  return pipe;
}

/*
 * Root pipe of the eSwitch FDB. Demuxes on source port (parser_meta.port_id):
 *   port_id == 0  (ingress from p0 wire)   -> wire_ingress_target (mark or passthrough)
 *   port_id == 1  (egress from mlx5_2 SF)   -> port 0 (p0 wire), so mlx5_2's RoCE
 *                                                ACKs/CNPs cross the cable back to mlx5_3
 *
 * The source-port match is the crux of the return path. A single root pipe in the
 * DEFAULT domain sees *all* FDB traffic, including mlx5_2's ACKs/CNPs. Routing those
 * through ECN_MARK would forward them to port 1 (looping them back to mlx5_2) — and
 * would also wrongly CE-mark them — so the sender never sees an ACK and the QP dies
 * with RETRY_EXC. Forwarding port_id==1 straight to port 0 here keeps mlx5_2's egress
 * off the mark pipe and puts it on the wire; no EGRESS-domain pipe is needed.
 *
 * wire_ingress_target selects where p0-wire ingress starts: the ECN_MARK/RANDOM_SAMPLE pipe
 * (0 < percent) or the passthrough pipe (--percent 0).
 */
static void create_port_demux_pipe(struct doca_flow_port *port, struct doca_flow_pipe *wire_ingress_target) {
  struct doca_flow_match match = {0};
  struct doca_flow_match match_mask = {0};
  struct doca_flow_fwd fwd = {.type = DOCA_FLOW_FWD_CHANGEABLE}; /* set per entry */
  struct doca_flow_fwd fwd_miss = {.type = DOCA_FLOW_FWD_DROP};
  struct doca_flow_pipe_cfg *cfg;
  struct doca_flow_pipe *pipe;
  doca_error_t err;

  match.parser_meta.port_id = UINT16_MAX;      /* variable — set per entry      */
  match_mask.parser_meta.port_id = UINT16_MAX; /* exact match on source port id */

  err = doca_flow_pipe_cfg_create(&cfg, port);
  crash_if_unsuccessful(err, "doca_flow_pipe_cfg_create (demux)");
  err = doca_flow_pipe_cfg_set_name(cfg, "PORT_DEMUX");
  crash_if_unsuccessful(err, "doca_flow_pipe_cfg_set_name (demux)");
  err = doca_flow_pipe_cfg_set_type(cfg, DOCA_FLOW_PIPE_BASIC);
  crash_if_unsuccessful(err, "doca_flow_pipe_cfg_set_type (demux)");
  err = doca_flow_pipe_cfg_set_domain(cfg, DOCA_FLOW_PIPE_DOMAIN_DEFAULT);
  crash_if_unsuccessful(err, "doca_flow_pipe_cfg_set_domain (demux)");
  err = doca_flow_pipe_cfg_set_is_root(cfg, true);
  crash_if_unsuccessful(err, "doca_flow_pipe_cfg_set_is_root (demux)");
  err = doca_flow_pipe_cfg_set_nr_entries(cfg, 2);
  crash_if_unsuccessful(err, "doca_flow_pipe_cfg_set_nr_entries (demux)");
  err = doca_flow_pipe_cfg_set_match(cfg, &match, &match_mask);
  crash_if_unsuccessful(err, "doca_flow_pipe_cfg_set_match (demux)");

  err = doca_flow_pipe_create(cfg, &fwd, &fwd_miss, &pipe);
  crash_if_unsuccessful(err, "doca_flow_pipe_create (demux)");
  doca_flow_pipe_cfg_destroy(cfg);

  struct doca_flow_match entry_match = {0};
  struct doca_flow_fwd entry_fwd;
  struct entry_batch_status status = {0};
  struct doca_flow_pipe_entry *entry;

  /* port 0 (p0 wire ingress) -> wire_ingress_target; batch, flush with next entry */
  entry_match.parser_meta.port_id = 0;
  memset(&entry_fwd, 0, sizeof(entry_fwd));
  entry_fwd.type = DOCA_FLOW_FWD_PIPE;
  entry_fwd.next_pipe = wire_ingress_target;
  err = doca_flow_pipe_basic_add_entry(0, pipe, &entry_match, 0, NULL, NULL, &entry_fwd,
                                       DOCA_FLOW_ENTRY_FLAGS_WAIT_FOR_BATCH, &status, &entry);
  crash_if_unsuccessful(err, "doca_flow_pipe_basic_add_entry (demux wire->target)");

  /* port 1 (mlx5_2 SF egress) -> p0 wire; flags=0 flushes the batch */
  entry_match.parser_meta.port_id = 1;
  memset(&entry_fwd, 0, sizeof(entry_fwd));
  entry_fwd.type = DOCA_FLOW_FWD_PORT;
  entry_fwd.port_id = 0;
  err = doca_flow_pipe_basic_add_entry(0, pipe, &entry_match, 0, NULL, NULL, &entry_fwd, 0, &status, &entry);
  crash_if_unsuccessful(err, "doca_flow_pipe_basic_add_entry (demux sf->wire)");

  err = doca_flow_entries_process(port, 0, 10000, 2);
  crash_if_unsuccessful(err, "doca_flow_entries_process (demux)");
  err = (status.failure || status.nb_processed != 2) ? DOCA_ERROR_BAD_STATE : DOCA_SUCCESS;
  crash_if_unsuccessful(err, "demux entry installation: %u/2 processed", status.nb_processed);

  DOCA_LOG_INFO("Port demux ready: p0 wire->wire_ingress_target, mlx5_2 SF->p0 wire");
}

static void print_stats(struct ecn_entries *entries) {
  struct doca_flow_resource_query ce_query, pass_query;
  doca_error_t err;

  /* entries->ce is NULL at --percent 0: no ECN_MARK pipe was ever built, so nothing to query. */
  uint64_t ce_pkts = 0;
  if (entries->ce != NULL) {
    err = doca_flow_resource_query_entry(entries->ce, &ce_query);
    crash_if_unsuccessful(err, "doca_flow_resource_query_entry CE");
    ce_pkts = ce_query.counter.total_pkts;
  }

  err = doca_flow_resource_query_entry(entries->passthrough, &pass_query);
  crash_if_unsuccessful(err, "doca_flow_resource_query_entry passthrough");
  uint64_t pass_pkts = pass_query.counter.total_pkts;

  uint64_t total = ce_pkts + pass_pkts;
  double pct = total > 0 ? (100.0 * (double)ce_pkts / (double)total) : 0.0;
  /* %g, not a fixed decimal count: --percent now goes well below 0.01%, where %.2f%% would
   * just print "0.00%" and hide whether marking is happening at all. */
  DOCA_LOG_INFO("CE marked: %lu, passthrough: %lu (%.4g%% marked)", ce_pkts, pass_pkts, pct);
}

static doca_error_t percent_callback(void *param, void *config) {
  struct ecn_app_config *cfg = config;
  double percent = atof((const char *)param);

  if (percent < 0.0 || percent > 100.0) {
    DOCA_LOG_ERR("--percent must be in [0, 100] (got '%s')", (const char *)param);
    return DOCA_ERROR_INVALID_VALUE;
  }
  cfg->random_percent = percent;
  return DOCA_SUCCESS;
}

static void register_ecn_params(void) {
  struct doca_argp_param *percent_param;
  doca_error_t err;

  err = doca_argp_param_create(&percent_param);
  crash_if_unsuccessful(err, "doca_argp_param_create (percent)");
  doca_argp_param_set_long_name(percent_param, "percent");
  doca_argp_param_set_description(percent_param,
                                  "Requested percentage of packets to mark, [0, 100] (fractional values allowed, e.g. "
                                  "0.1). 0 and 100 are exact; anything in between is rounded down to the nearest "
                                  "power-of-two fraction: 50, 25, 12.5, .... Default: 100");
  doca_argp_param_set_callback(percent_param, percent_callback);
  doca_argp_param_set_type(percent_param, DOCA_ARGP_TYPE_STRING);
  err = doca_argp_register_param(percent_param);
  crash_if_unsuccessful(err, "doca_argp_register_param (percent)");
}

int main(int argc, char **argv) {
  doca_error_t err;

  err = doca_log_backend_create_standard();
  crash_if_unsuccessful(err, "doca_log_backend_create_standard");

  struct doca_log_backend *sdk_log;
  err = doca_log_backend_create_with_file_sdk(stderr, &sdk_log);
  crash_if_unsuccessful(err, "doca_log_backend_create_with_file_sdk");

  err = doca_log_backend_set_sdk_level(sdk_log, DOCA_LOG_LEVEL_WARNING);
  crash_if_unsuccessful(err, "doca_log_backend_set_sdk_level");

  struct ecn_app_config app_cfg = {.random_percent = 100.0};

  err = doca_argp_init("doca_flow_ecn", &app_cfg);
  crash_if_unsuccessful(err, "doca_argp_init");

  doca_argp_set_dpdk_program(initialize_dpdk);
  register_ecn_params();

  err = doca_argp_start(argc, argv);
  crash_if_unsuccessful(err, "doca_argp_start");

  /* PF0 only: DOCA manages PF0's FDB via HWS root pipes (highest priority).
   * fdb_def_rule_en=1 keeps the kernel's default FDB rules for PF1 so that
   * mlx5_3's egress traffic exits via p1 wire uplink. DOCA HWS root pipes on
   * PF0 override the kernel defaults for PF0 ingress and egress. */
  struct doca_dev *dev = open_and_probe_dev(0, "dv_flow_en=2,fdb_def_rule_en=1,repr_matching_en=0,representor=sf0");

  configure_and_start_dpdk_port(dev);

  initialize_doca_flow();

  struct doca_flow_port *port = port_start(dev);          /* DPDK 0: PF0 uplink */
  struct doca_flow_port *sf_rep_port = rep_port_start(1); /* DPDK 1: PF0 SF rep (mlx5_2) */

  /* INGRESS_PASSTHROUGH: miss target of ECN_MARK/RANDOM_SAMPLE, and --percent 0's only route —
   * non-ECT / already-CE / not-selected / never-selected wire packets still reach mlx5_2
   * (port 1) untouched. Counted, so marking can be observed live. */
  struct doca_flow_pipe *ingress_pass = create_fwd_pipe(port, "INGRESS_PASSTHROUGH", DOCA_FLOW_PIPE_DOMAIN_DEFAULT, false, 1,
                                                        /*with_counter=*/true);
  struct doca_flow_pipe_entry *pass_entry = add_fwd_entry(ingress_pass, port, "ingress passthrough", /*with_counter=*/true);

  /* ECN_MARK only needs to exist if a nonzero percentage can reach it. At --percent 0 nothing
   * ever marks, so there's no pipe to build (entries.ce stays NULL — see print_stats). */
  struct doca_flow_pipe *pipe = NULL;
  struct ecn_entries entries = {0};
  if (app_cfg.random_percent > 0.0) {
    pipe = create_ecn_mark_pipe(port, ingress_pass);
    entries = add_ecn_entries(pipe, port);
  }
  entries.passthrough = pass_entry;

  /* RANDOM_SAMPLE pre-filters p0 wire ingress by a HW random value before ECN_MARK ever sees
   * it. Only built for 0 < percent < 100 — at 100% everything goes straight to ECN_MARK (no
   * need to sample first), at 0% everything goes straight to ingress_pass. */
  uint16_t random_mask = 0;
  struct doca_flow_pipe *wire_ingress_target;
  if (app_cfg.random_percent >= 100.0) {
    wire_ingress_target = pipe;
  } else if (app_cfg.random_percent <= 0.0) {
    wire_ingress_target = ingress_pass;
  } else {
    random_mask = get_random_mask(app_cfg.random_percent);
    wire_ingress_target = create_random_sample_pipe(port, pipe, ingress_pass, random_mask);
  }

  /* PORT_DEMUX (root): splits by source port. p0 wire ingress -> wire_ingress_target;
   * mlx5_2 SF egress (ACKs/CNPs) -> p0 wire so they return to mlx5_3. Replaces the old
   * EGRESS_FORWARD pipe, which never fired because the DEFAULT-domain root pipe made the
   * forwarding decision before egress processing. */
  create_port_demux_pipe(port, wire_ingress_target);

  signal(SIGINT, signal_handler);
  signal(SIGTERM, signal_handler);

  if (app_cfg.random_percent >= 100.0) {
    DOCA_LOG_INFO("Marking every IPv4 packet — Ctrl-C to stop");
  } else if (app_cfg.random_percent <= 0.0) {
    DOCA_LOG_INFO("Marking no packets — Ctrl-C to stop");
  } else {
    DOCA_LOG_INFO("Marking ~%.4g%% of IPv4 packets — Ctrl-C to stop", 100.0 / (random_mask + 1));
  }

  while (g_running) {
    sleep(1);
    print_stats(&entries);
  }

  doca_flow_port_stop(sf_rep_port);
  doca_flow_port_stop(port);
  doca_flow_destroy();
  doca_argp_destroy();

  return EXIT_SUCCESS;
}
