#!/usr/bin/env bash
#
# Target-side: install the PARTICIPANT repo in the tutorial user's home, with no git history.
#
# This is not sync.sh. sync.sh maintains OUR repo on a machine as a live git checkout that can be
# fast-forwarded; this installs a plain directory of files and deletes .git before anything is
# visible to a participant.
#
# WHY .git GOES. The participant repo is regenerated by
# admin/update_participants_repo_on_github.py, and its history therefore contains every earlier
# state of the exercise -- including the period when solutions
# shipped alongside it. A participant sitting on the machine with a checkout could read all of that
# with `git log -p`. Removing .git removes that from the machine.
#
# It removes it FROM THE MACHINE and nothing more. If the participant repo is public on GitHub, the
# same history is a `git clone` away from any laptop, and this script does not change that. Rewriting
# or truncating the remote's history is the only thing that does.
#
# BECAUSE .git IS GONE there is no such thing as updating this tree: with no remote, no branch and no
# index, the only way to move it forward is to replace it. So the default refuses to touch a
# destination that already exists, and --force replaces it wholesale. On a machine somebody has been
# working on, --force deletes their exercise work. There is no way for this script to tell the
# difference -- that is the cost of taking the history away.
#
# fleet.py pipes this over stdin (`ssh <host> bash -s -- <args>`), so it MUST stay self-contained:
# it cannot source anything else from the repo, because on a fresh machine nothing else is there
# yet. It is also meant to be runnable by hand on a machine the fleet tool cannot reach.
#
# Machine-readable results are printed as '@@key=value' lines; everything else is log output.
#
set -euo pipefail

REPO_URL=""
BRANCH="main"
TUSER="s26t"
DEST=""
FORCE=0

while [ $# -gt 0 ]; do
	case "$1" in
		--repo)   REPO_URL="$2"; shift 2 ;;
		--branch) BRANCH="$2";   shift 2 ;;
		--user)   TUSER="$2";    shift 2 ;;
		--dest)   DEST="$2";     shift 2 ;;
		--force)  FORCE=1;       shift ;;
		*) echo "unknown argument: $1" >&2; exit 2 ;;
	esac
done

DEST="${DEST:-/home/$TUSER/$(basename "${REPO_URL%.git}")}"

die()  { echo "ERROR: $*" >&2; exit 1; }
emit() { printf '@@%s=%s\n' "$1" "$2"; }

[ -n "$REPO_URL" ] || die "--repo is required"
command -v git >/dev/null 2>&1 || die "git is not installed"
id -u "$TUSER" >/dev/null 2>&1 || die "user '$TUSER' does not exist (run the 'user' verb first)"

# Own the checkout as the tutorial user: participants have to edit and rebuild in this tree, so a
# root-owned or admin-owned copy would break the exercise. When we are already logged in as that
# user there is nothing to elevate, which is the normal case.
if [ "$(id -un)" = "$TUSER" ]; then
	as_tuser() { "$@"; }
else
	sudo -n true 2>/dev/null || die "passwordless sudo needed to act as '$TUSER' (logged in as $(id -un))"
	as_tuser() { sudo -n -u "$TUSER" -H "$@"; }
fi

# Kept to ONE line: fleet.py's summary table shows the last line a failing script printed, so a
# message wrapped over three of them arrives in the NOTE column as a dangling fragment.
if [ -e "$DEST" ] && [ "$FORCE" -eq 0 ]; then
	die "$DEST already exists and was left untouched; re-run with --force to delete and reinstall it (this destroys any work in that tree)"
fi

PARENT="$(dirname "$DEST")"
BASE="$(basename "$DEST")"
[ -d "$PARENT" ] || die "$PARENT does not exist"

# Staged next to the destination rather than in /tmp, so the final rename is a move within one
# filesystem: the tree is either the old one or the new one, never half-written.
TMP="$PARENT/.$BASE.new.$$"
OLD="$PARENT/.$BASE.old.$$"

cleanup() { as_tuser rm -rf "$TMP"; }
trap cleanup EXIT

as_tuser rm -rf "$TMP"

# --depth 1 for the obvious reason and one less obvious one: the history never lands on the machine
# in the first place, so the window between clone and `rm -rf .git` holds nothing worth reading.
echo "cloning $REPO_URL ($BRANCH) -> $DEST"
as_tuser git clone --quiet --depth 1 --branch "$BRANCH" "$REPO_URL" "$TMP"

sha="$(as_tuser git -C "$TMP" rev-parse --short HEAD)"
subject="$(as_tuser git -C "$TMP" log -1 --format=%s)"

# The point of this script. Written as `if` rather than `[ ... ] && die` because the false branch of
# an && list is exactly the good case here, and under `set -e` that is a trap worth not laying.
as_tuser rm -rf "$TMP/.git"
if [ -e "$TMP/.git" ]; then
	die "failed to remove $TMP/.git -- refusing to install a tree with history"
fi

# Belt and braces: a stray .git anywhere in the tree (a submodule, a checked-in fixture) would put
# history back on the machine through the side door.
leftover="$(as_tuser find "$TMP" -name .git -print -quit)"
if [ -n "$leftover" ]; then
	die "found $leftover after the clone -- refusing to install a tree with history"
fi

if [ -e "$DEST" ]; then
	as_tuser mv "$DEST" "$OLD"
	action="replaced"
else
	action="installed"
fi

if ! as_tuser mv "$TMP" "$DEST"; then
	if [ -e "$OLD" ]; then
		as_tuser mv "$OLD" "$DEST"
	fi
	die "could not move $TMP into place"
fi

trap - EXIT
as_tuser rm -rf "$OLD"

emit action      "$action"
emit sha         "$sha"
emit dest        "$DEST"
emit git_removed "yes"
emit subject     "$subject"
